name: LaTeX
on: [push]
jobs:
  build_latex:
   runs-on: ubuntu-latest   
   steps: 
     - name: Set up Git Repository
       uses: actions/checkout@v3
     - name: Compile LaTeX document
       uses: xu-cheng/latex-actions@v2
       with:
         root_file: main.tex
         latexmx_use_xelatex: true
     - name: Check out
       run: ls
     - name: Release
       uses: softprops/action-gh-release@v1
       if: startsWith(github.ref, 'refs/tags/')
       with:
        files: main.pdf
       
     
         
